[phases.setup]
nixPkgs = ["nodejs_20", "nginx"]

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = [
  "npm run build",
  "mkdir -p /usr/share/nginx/html",
  "cp -r dist/* /usr/share/nginx/html/",
]

[start]
cmd = "mkdir -p /var/log/nginx && nginx -g 'daemon off;'"
